## %timeit  (to gather runtime for a single line of code)

In [35]:
# Create a range object that goes from 0 to 5
nums = range(1,12,2)
nums_list = list(nums)
%timeit nums_list = list(range(1,12,2))
print(nums_list)

# *************************
# Create a new list of odd numbers from 1 to 11 by unpacking a range object
nums_list2 = [*range(1,12,2)]
%timeit nums_list2 = [*range(1,12,2)]
print(nums_list2)

1.68 µs ± 345 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
[1, 3, 5, 7, 9, 11]
1.16 µs ± 124 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
[1, 3, 5, 7, 9, 11]


## list VS numpy array

In [25]:
import numpy as np

nums= [*range(5)]
%timeit nums= [*range(5)]
print(nums)
#***********************************
nums_np = np.array(range(5))
%timeit nums_np = np.array(range(5))
print(nums_np)

949 ns ± 82 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
[0, 1, 2, 3, 4]
22.2 µs ± 1.71 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
[0 1 2 3 4]


In [27]:
nums_pow = [num**2 for num in nums]
%timeit nums_pow = [num**2 for num in nums]
print(nums_pow)
#************************************
nums_np_pow = nums_np ** 2
%timeit nums_np_pow = nums_np ** 2
print(nums_np_pow)

5.67 µs ± 871 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
[0, 1, 4, 9, 16]
3.98 µs ± 499 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
[ 0  1  4  9 16]


#### As you above, list may be faster than np.array about consisting list, but in operational transactions, np.array is faster than list.

In [30]:
nums2 = [[1, 2, 3], [4, 5, 6]]

nums2_np = np.array([[1, 2, 3], [4, 5, 6]])

%timeit nums2[0][1] 
print(nums2[0][1])
%timeit nums2_np[0, 1]
print(nums2_np[0, 1])

%timeit nums2[0]
print(nums2[0])
%timeit nums2_np[0]
print(nums2_np[0])

%timeit [row[0] for row in nums2]
print([row[0] for row in nums2])
%timeit nums2_np[:,0]
print(nums2_np[:,0])

178 ns ± 19 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
2
359 ns ± 3.01 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
2
107 ns ± 0.553 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
[1, 2, 3]
371 ns ± 3.19 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
[1 2 3]
926 ns ± 97.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
[1, 4]
629 ns ± 5.37 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
[1 4]


In [32]:
nums = [-2, -1, 0, 1, 2]

nums_np = np.array([-2, -1, 0, 1, 2])

%timeit [num for num in nums if num>0] 
print([num for num in nums if num>0])
%timeit nums_np[nums_np>0]
print(nums_np[nums_np>0])

1.21 µs ± 3.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
[1, 2]
9.3 µs ± 27.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
[1 2]


## 5 runs with 25 loops per each run?
A list of 480 superheroes has been loaded into your session (called heroes). You'd like to analyze the runtime for converting this heroes list into a set. Instead of relying on the default settings for %timeit, you'd like to only use 5 runs and 25 loops per each run.

In [11]:
a = [1, 2, 3]
heroes = a * 480
%timeit -r5 -n25 set(heroes)

43.2 µs ± 1.32 µs per loop (mean ± std. dev. of 5 runs, 25 loops each)


In [33]:
# Create a list using the formal name
formal_list = list()
%timeit formal_list = list()
print(formal_list)

# Create a list using the literal syntax
literal_list = []
%timeit literal_list = []
print(literal_list)

339 ns ± 142 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
[]
107 ns ± 20.9 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
[]


## %%timeit          (to get the runtime for multiple lines of code)

### normal loop VS built-in function

In [41]:
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']
%%timeit
names_uppercase = []

for name in names:
    names_uppercase.append(name.upper())

2.63 µs ± 171 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [42]:
print(names_uppercase)

['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']


In [43]:
%%timeit
# Use map to apply str.upper to each element in names
names_map  = map(str.upper, names)

# Unpack names_map into a list
names_uppercase = [*names_map]

2.4 µs ± 133 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [44]:
print(names_uppercase)

['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']


#### As you above, built-in function is faster than loop.

### normal loop VS list comprehension VS unpack

In [45]:
%%timeit
# Rewrite the for loop to use enumerate
indexed_names = []
for i,name in enumerate(names, 3):
    index_name = (i,name)
    indexed_names.append(index_name) 

3.19 µs ± 574 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [46]:
print(indexed_names)

[(3, 'Jerry'), (4, 'Kramer'), (5, 'Elaine'), (6, 'George'), (7, 'Newman')]


In [47]:
%%timeit
# Rewrite the above for loop using list comprehension
indexed_names_comp = [(i,name) for i,name in enumerate(names, 3)]

2.87 µs ± 503 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [48]:
print(indexed_names_comp)

[(3, 'Jerry'), (4, 'Kramer'), (5, 'Elaine'), (6, 'George'), (7, 'Newman')]


In [49]:
%%timeit
# Unpack an enumerate object with a starting index of one
indexed_names_unpack = [*enumerate(names, 3)]

1.5 µs ± 166 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [50]:
print(indexed_names_unpack)

[(3, 'Jerry'), (4, 'Kramer'), (5, 'Elaine'), (6, 'George'), (7, 'Newman')]


#### As you above, list comprehension is faster than normal loop, unpack is faster than list comprehension. 

## runtime for functions

In [3]:
heroes = ['superman', 'batman', 'flash']
hts = [175, 170, 175]
wts = [75, 70, 75]

def convert_units(heroes, heights, weights):

    new_hts = [ht * 0.39370  for ht in heights]
    new_wts = [wt * 2.20462  for wt in weights]

    hero_data = {}

    for i,hero in enumerate(heroes):
        hero_data[hero] = (new_hts[i], new_wts[i])

    return hero_data

In [4]:
%timeit convert_units(heroes, hts, wts)

5.81 µs ± 134 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [5]:
%load_ext line_profiler

The line_profiler extension is already loaded. To reload it, use:
  %reload_ext line_profiler


In [7]:
%lprun -f convert_units convert_units(heroes, hts, wts)

Timer unit: 1e-07 s

Total time: 4.71e-05 s
File: <ipython-input-3-c5e612a7b692>
Function: convert_units at line 5

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
     5                                           def convert_units(heroes, heights, weights):
     6                                           
     7         1        129.0    129.0     27.4      new_hts = [ht * 0.39370  for ht in heights]
     8         1         81.0     81.0     17.2      new_wts = [wt * 2.20462  for wt in weights]
     9                                           
    10         1         26.0     26.0      5.5      hero_data = {}
    11                                           
    12         4        124.0     31.0     26.3      for i,hero in enumerate(heroes):
    13         3         89.0     29.7     18.9          hero_data[hero] = (new_hts[i], new_wts[i])
    14                                           
    15         1         22.0     22.0      4.7      return hero_data

#### This provide you to find potential boottlenecks.

## memory usage for functions with different types data (list vs. np.array)

In [39]:
import random
import numpy as np
sample_indices = 150 * random.sample(range(1, 150), 149)
hts=random.sample(range(1, 200), 199)
wts=random.sample(range(1, 200), 199)
print(len(sample_indices))

22350


In [40]:
#%load_ext memory_profiler
from oop_package import calc_bmi_lists
%mprun -f calc_bmi_lists calc_bmi_lists(sample_indices, hts, wts)

Filename: C:\Users\dogan\Documents\JAVA-Applications\Python\Datacamp\oop_package\oop_deneme1.py

Line #    Mem usage    Increment   Line Contents
================================================
    47     66.1 MiB     66.1 MiB   def calc_bmi_lists(sample_indices, hts, wts):
    48                             
    49                                 # Gather sample heights and weights as lists
    50     66.2 MiB      0.0 MiB       s_hts = [hts[i] for i in sample_indices]
    51     66.2 MiB      0.0 MiB       s_wts = [wts[i] for i in sample_indices]
    52                             
    53                                 # Convert heights from cm to m and square with list comprehension
    54     66.4 MiB      0.1 MiB       s_hts_m_sqr = [(ht / 100) ** 2 for ht in s_hts]
    55                             
    56                                 # Calculate BMIs as a list with list comprehension
    57     67.0 MiB      0.1 MiB       bmis = [s_wts[i] / s_hts_m_sqr[i] for i in range(len(sample_indices))]
    58                             
    59     67.0 MiB      0.0 MiB       return bmis

#### How much memory do the array indexing and broadcasting lines of code consume in the calc_bmi_array() function? (i.e., what is the total sum of the Increment column for these four lines of code?)

Answer: 0.2 MiB

In [1]:
import random
import numpy as np
sample_indices = np.array(150 * random.sample(range(1, 150), 149))
hts=np.array(random.sample(range(1, 200), 199))
wts=np.array(random.sample(range(1, 200), 199))
print(len(sample_indices))

22350


In [3]:
%load_ext memory_profiler
from oop_package import calc_bmi_arrays
%mprun -f calc_bmi_arrays calc_bmi_arrays(sample_indices, hts, wts)

Filename: C:\Users\dogan\Documents\JAVA-Applications\Python\Datacamp\oop_package\oop_deneme1.py

Line #    Mem usage    Increment   Line Contents
================================================
    61     73.0 MiB     73.0 MiB   def calc_bmi_arrays(sample_indices, hts, wts):
    62                             
    63                                 # Gather sample heights and weights as arrays
    64     73.1 MiB      0.2 MiB       s_hts = hts[sample_indices]
    65     73.2 MiB      0.1 MiB       s_wts = wts[sample_indices]
    66                             
    67                                 # Convert heights from cm to m and square with broadcasting
    68     74.4 MiB      1.2 MiB       s_hts_m_sqr = (s_hts / 100) ** 2
    69                             
    70                                 # Calculate BMIs as an array using broadcasting
    71     74.6 MiB      0.2 MiB       bmis = s_wts / s_hts_m_sqr
    72                             
    73     74.6 MiB      0.0 MiB       return bmis

#### How much memory do the array indexing and broadcasting lines of code consume in the calc_bmi_array() function? (i.e., what is the total sum of the Increment column for these four lines of code?)

Answer: 1.7 MiB

#### alternative way for seeing memory usage 

In [11]:
import sys 
num_list = [*range(1000)]
sys.getsizeof(num_list)

9112